# Supabase local development configuration
project_id = "ihavtogobadly-com"

[api]
enabled = true
port = 54321

[db]
port = 54322

[auth]
enabled = true
site_url = "http://localhost:5173"
enable_signup = true

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"